# Generated by Django 2.1.7 on 2019-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mentor', models.CharField(default='sejal thakkar', max_length=100)),
                ('std_no', models.IntegerField(blank=True, null=True)),
                ('father', models.IntegerField(blank=True, null=True)),
                ('mother', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
