# Generated by Django 2.1.7 on 2019-04-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190413_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='std_no',
            new_name='stdno',
        ),
    ]
