# Generated by Django 2.1.7 on 2019-04-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190413_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stdno',
            new_name='number',
        ),
    ]
